AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The notification system for blog.aotoki.me

Parameters:
  Namespace:
    Type: String
    Default: "blog-notifier"
    Description: "The namespace for the blog notifier"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Runtime: ruby3.3
    CodeUri: .
    Handler: config/lambda.Lambda.call
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON
    Layers:
      - !Ref GemLayer
    Environment:
      Variables:
        NAMESPACE: !Ref Namespace
        AWS_LAMBDA_EXEC_WRAPPER: /var/task/bin/bootstrap

Resources:
  GemLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blog-notifier
      Description: The application core for the blog notifier
      ContentUri: .
      CompatibleRuntimes:
        - ruby3.3
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  FetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Namespace}_fetcher"
      Description: "The fetcher function to get the latest blog posts"
    Metadata:
      BuildMethod: makefile
