AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The notification system for blog.aotoki.me

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 2048
    Runtime: ruby3.3
    CodeUri: .
    Handler: config/app.Lambda.call
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON
    Layers:
      - !Ref GemLayer
    Environment:
      Variables:
        AWS_LAMBDA_EXEC_WRAPPER: /var/task/bin/bootstrap

Resources:
  GemLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blog-notifier
      Description: The application core for the blog notifier
      ContentUri: .
      CompatibleRuntimes:
        - ruby3.3
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  FetcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "blog-notifier_fetcher"
      Description: "The fetcher function to get the latest blog posts"
    Metadata:
      BuildMethod: makefile
